### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by LLL06250901** [Retinal-Research/OTE-GAN#1]
您好，请问数据集怎么导入？

**Comment by ChongQingNoSubway** [comment]
下载 CSV: https://github.com/HzFu/EyeQ
数据集是 EYEPACS: https://www.kaggle.com/c/diabetic-retinopathy-detection/data
unsupervised experiment dataloader -> EyeQ.py -> replace the root and file_dir (root directory of eyepacs dataset and CSV file)
degradation experiment dataloader -> EyeQ.py -> replace rootHQ and rootPQ (root directory of high quality and degradation data)

**Comment by LLL06250901** [comment]
谢谢您

**Comment by LLL06250901** [comment]
谢谢您
