### ISSUE TITLE
full reference experiment 

### ISSUE THREAD

**Issue by Body123** [Retinal-Research/OTE-GAN#4]
I want to ask about rows for example the row "ours" this calculated between the degraded images and their corresponding enhancement images or (between the original high quality images and their enhancement)

![15](https://github.com/Retinal-Research/OTE-GAN/assets/24945076/0d0e31d9-8134-47ea-9d9b-ea2085dbe54f)

**Comment by ChongQingNoSubway** [comment]
The metrics were calculated between the original high-quality images and their enhancement. 
The degradation model refers to  https://github.com/HzFu/EyeQ_Enhancement

**Comment by Body123** [comment]
can I know how you choose the best checkpoint to do the full reference experiment because when I see the code you save every check point after each iteration so what criteria to choose the best checkpoint, please?

**Comment by ChongQingNoSubway** [comment]
At the time of our experiments, the last 50 were generally chosen as a check, and the best performance was selected. 
You can customize a certain amount of testing images at each save checkpoint and then calculate PSNR and SSIM.
